/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseDropdown: typeof import('./src/components/base/dropdown/BaseDropdown.vue')['default']
    BaseEmpty: typeof import('./src/components/base/empty/BaseEmpty.vue')['default']
    BaseExpandDropDown: typeof import('./src/components/base/dropdown/BaseExpandDropDown.vue')['default']
    BaseFilter: typeof import('./src/components/base/filter/BaseFilter.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BaseLoading: typeof import('./src/components/base/loading/BaseLoading.vue')['default']
    BaseMenu: typeof import('./src/components/base/menu/BaseMenu.vue')['default']
    BasePagination: typeof import('./src/components/base/pagination/BasePagination.vue')['default']
    BasePopup: typeof import('./src/components/base/popup/BasePopup.vue')['default']
    BaseSelect: typeof import('./src/components/base/select/BaseSelect.vue')['default']
    BaseTable: typeof import('./src/components/base/table/BaseTable.vue')['default']
    BaseTabs: typeof import('./src/components/base/tabs/BaseTabs.vue')['default']
    DatePicker: typeof import('./src/components/base/input/DatePicker.vue')['default']
    ElAffixTableColumn: typeof import('element-plus/es')['ElAffixTableColumn']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InputSearch: typeof import('./src/components/base/input/InputSearch.vue')['default']
    MoreFilter: typeof import('./src/components/base/filter/MoreFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
